services:
  - type: web
    name: sensory-app
    env: node
    branch: main
    repo: https://github.com/Hospital2025/sensory-.git
    installCommand: npm install
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: postgresql://…
      - key: NODE_ENV
        value: production
      - key: RENDER_USE_BUN
        value: "false"
